import typescript from '@rollup/plugin-typescript';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import scss from 'rollup-plugin-scss';

const isProd = (process.env.BUILD === 'production');

const banner =
  `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default [
  {
    input: './src/style/snippet/styles.sass',
    output: {
      file: './src/style/snippet/styles.css',
      format: 'es'
    },
    plugins: [
      scss({
        output: './src/style/snippet/timeline-snippet.css',
        failOnError: true,
        runtime: require("sass"),
        indentedSyntax: true,
        watch: './src/style/snippet',
        prefix: "@use 'sass:math'\n",
        outputStyle: isProd ? 'compressed' : undefined
      })
    ]
  },
];